### ISSUE TITLE
Tuah, blog links not working

### ISSUE THREAD

**Issue by KorigamiK** [iyksh/Hawk#2]
Links don't seem to work. Readme is a bit lacking
- https://iyksh.github.io/blog/
- https://iyksh.github.io/blog/sniffer/

**Comment by iyksh** [comment]
Hello, I changed the location within the site because in the old tutorial I basically explained how to deal with different protocols using Rust, and left the rest of the implementation as an exercise for the reader. I just removed the project but kept the protocols link at: https://yks.netlify.app/protocols/

ANyways, thanks for reminding me to make the changes
